// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock.go -typed -package=calendar
//

// Package calendar is a generated GoMock package.
package calendar

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockService) CreateEvent(ctx context.Context, r CreateRequest) (Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, r)
	ret0, _ := ret[0].(Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockServiceMockRecorder) CreateEvent(ctx, r any) *MockServiceCreateEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockService)(nil).CreateEvent), ctx, r)
	return &MockServiceCreateEventCall{Call: call}
}

// MockServiceCreateEventCall wrap *gomock.Call
type MockServiceCreateEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateEventCall) Return(arg0 Event, arg1 error) *MockServiceCreateEventCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateEventCall) Do(f func(context.Context, CreateRequest) (Event, error)) *MockServiceCreateEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateEventCall) DoAndReturn(f func(context.Context, CreateRequest) (Event, error)) *MockServiceCreateEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DayEvents mocks base method.
func (m *MockService) DayEvents(ctx context.Context, userID uuid.UUID) ([]Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DayEvents", ctx, userID)
	ret0, _ := ret[0].([]Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DayEvents indicates an expected call of DayEvents.
func (mr *MockServiceMockRecorder) DayEvents(ctx, userID any) *MockServiceDayEventsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DayEvents", reflect.TypeOf((*MockService)(nil).DayEvents), ctx, userID)
	return &MockServiceDayEventsCall{Call: call}
}

// MockServiceDayEventsCall wrap *gomock.Call
type MockServiceDayEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDayEventsCall) Return(arg0 []Event, arg1 error) *MockServiceDayEventsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDayEventsCall) Do(f func(context.Context, uuid.UUID) ([]Event, error)) *MockServiceDayEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDayEventsCall) DoAndReturn(f func(context.Context, uuid.UUID) ([]Event, error)) *MockServiceDayEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteEvent mocks base method.
func (m *MockService) DeleteEvent(ctx context.Context, r DeleteRequest) (Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, r)
	ret0, _ := ret[0].(Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockServiceMockRecorder) DeleteEvent(ctx, r any) *MockServiceDeleteEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockService)(nil).DeleteEvent), ctx, r)
	return &MockServiceDeleteEventCall{Call: call}
}

// MockServiceDeleteEventCall wrap *gomock.Call
type MockServiceDeleteEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeleteEventCall) Return(arg0 Event, arg1 error) *MockServiceDeleteEventCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeleteEventCall) Do(f func(context.Context, DeleteRequest) (Event, error)) *MockServiceDeleteEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeleteEventCall) DoAndReturn(f func(context.Context, DeleteRequest) (Event, error)) *MockServiceDeleteEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Events mocks base method.
func (m *MockService) Events(ctx context.Context, userID uuid.UUID) ([]Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", ctx, userID)
	ret0, _ := ret[0].([]Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Events indicates an expected call of Events.
func (mr *MockServiceMockRecorder) Events(ctx, userID any) *MockServiceEventsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockService)(nil).Events), ctx, userID)
	return &MockServiceEventsCall{Call: call}
}

// MockServiceEventsCall wrap *gomock.Call
type MockServiceEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceEventsCall) Return(arg0 []Event, arg1 error) *MockServiceEventsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceEventsCall) Do(f func(context.Context, uuid.UUID) ([]Event, error)) *MockServiceEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceEventsCall) DoAndReturn(f func(context.Context, uuid.UUID) ([]Event, error)) *MockServiceEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MonthEvents mocks base method.
func (m *MockService) MonthEvents(ctx context.Context, userID uuid.UUID) ([]Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonthEvents", ctx, userID)
	ret0, _ := ret[0].([]Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MonthEvents indicates an expected call of MonthEvents.
func (mr *MockServiceMockRecorder) MonthEvents(ctx, userID any) *MockServiceMonthEventsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonthEvents", reflect.TypeOf((*MockService)(nil).MonthEvents), ctx, userID)
	return &MockServiceMonthEventsCall{Call: call}
}

// MockServiceMonthEventsCall wrap *gomock.Call
type MockServiceMonthEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceMonthEventsCall) Return(arg0 []Event, arg1 error) *MockServiceMonthEventsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceMonthEventsCall) Do(f func(context.Context, uuid.UUID) ([]Event, error)) *MockServiceMonthEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceMonthEventsCall) DoAndReturn(f func(context.Context, uuid.UUID) ([]Event, error)) *MockServiceMonthEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateEvent mocks base method.
func (m *MockService) UpdateEvent(ctx context.Context, event Event) (Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", ctx, event)
	ret0, _ := ret[0].(Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockServiceMockRecorder) UpdateEvent(ctx, event any) *MockServiceUpdateEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockService)(nil).UpdateEvent), ctx, event)
	return &MockServiceUpdateEventCall{Call: call}
}

// MockServiceUpdateEventCall wrap *gomock.Call
type MockServiceUpdateEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateEventCall) Return(arg0 Event, arg1 error) *MockServiceUpdateEventCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateEventCall) Do(f func(context.Context, Event) (Event, error)) *MockServiceUpdateEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateEventCall) DoAndReturn(f func(context.Context, Event) (Event, error)) *MockServiceUpdateEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WeekEvents mocks base method.
func (m *MockService) WeekEvents(ctx context.Context, userID uuid.UUID) ([]Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WeekEvents", ctx, userID)
	ret0, _ := ret[0].([]Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WeekEvents indicates an expected call of WeekEvents.
func (mr *MockServiceMockRecorder) WeekEvents(ctx, userID any) *MockServiceWeekEventsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WeekEvents", reflect.TypeOf((*MockService)(nil).WeekEvents), ctx, userID)
	return &MockServiceWeekEventsCall{Call: call}
}

// MockServiceWeekEventsCall wrap *gomock.Call
type MockServiceWeekEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceWeekEventsCall) Return(arg0 []Event, arg1 error) *MockServiceWeekEventsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceWeekEventsCall) Do(f func(context.Context, uuid.UUID) ([]Event, error)) *MockServiceWeekEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceWeekEventsCall) DoAndReturn(f func(context.Context, uuid.UUID) ([]Event, error)) *MockServiceWeekEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
