// Code generated by MockGen. DO NOT EDIT.
// Source: internal/cache/contract.go
//
// Generated by this command:
//
//	mockgen -source=internal/cache/contract.go -destination=internal/cache/mock.go -package=cache
//

// Package cache is a generated GoMock package.
package cache

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache[K comparable, V any] struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder[K, V]
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder[K comparable, V any] struct {
	mock *MockCache[K, V]
}

// NewMockCache creates a new mock instance.
func NewMockCache[K comparable, V any](ctrl *gomock.Controller) *MockCache[K, V] {
	mock := &MockCache[K, V]{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder[K, V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache[K, V]) EXPECT() *MockCacheMockRecorder[K, V] {
	return m.recorder
}

// Cap mocks base method.
func (m *MockCache[K, V]) Cap() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cap")
	ret0, _ := ret[0].(int)
	return ret0
}

// Cap indicates an expected call of Cap.
func (mr *MockCacheMockRecorder[K, V]) Cap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cap", reflect.TypeOf((*MockCache[K, V])(nil).Cap))
}

// Get mocks base method.
func (m *MockCache[K, V]) Get(key K) (V, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder[K, V]) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache[K, V])(nil).Get), key)
}

// Len mocks base method.
func (m *MockCache[K, V]) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockCacheMockRecorder[K, V]) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockCache[K, V])(nil).Len))
}

// Set mocks base method.
func (m *MockCache[K, V]) Set(key K, value V) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, value)
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder[K, V]) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache[K, V])(nil).Set), key, value)
}
