// Code generated by MockGen. DO NOT EDIT.
// Source: internal/metrics/contract.go
//
// Generated by this command:
//
//	mockgen -source=internal/metrics/contract.go -destination=internal/metrics/mock.go -package=metrics
//

// Package metrics is a generated GoMock package.
package metrics

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncCacheGet mocks base method.
func (m *MockMetrics) IncCacheGet() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncCacheGet")
}

// IncCacheGet indicates an expected call of IncCacheGet.
func (mr *MockMetricsMockRecorder) IncCacheGet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncCacheGet", reflect.TypeOf((*MockMetrics)(nil).IncCacheGet))
}

// IncCacheSet mocks base method.
func (m *MockMetrics) IncCacheSet() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncCacheSet")
}

// IncCacheSet indicates an expected call of IncCacheSet.
func (mr *MockMetricsMockRecorder) IncCacheSet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncCacheSet", reflect.TypeOf((*MockMetrics)(nil).IncCacheSet))
}

// IncFailed mocks base method.
func (m *MockMetrics) IncFailed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFailed")
}

// IncFailed indicates an expected call of IncFailed.
func (mr *MockMetricsMockRecorder) IncFailed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFailed", reflect.TypeOf((*MockMetrics)(nil).IncFailed))
}

// IncOrders mocks base method.
func (m *MockMetrics) IncOrders() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncOrders")
}

// IncOrders indicates an expected call of IncOrders.
func (mr *MockMetricsMockRecorder) IncOrders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncOrders", reflect.TypeOf((*MockMetrics)(nil).IncOrders))
}

// IncPostgresGet mocks base method.
func (m *MockMetrics) IncPostgresGet() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncPostgresGet")
}

// IncPostgresGet indicates an expected call of IncPostgresGet.
func (mr *MockMetricsMockRecorder) IncPostgresGet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncPostgresGet", reflect.TypeOf((*MockMetrics)(nil).IncPostgresGet))
}

// IncPostgresSet mocks base method.
func (m *MockMetrics) IncPostgresSet() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncPostgresSet")
}

// IncPostgresSet indicates an expected call of IncPostgresSet.
func (mr *MockMetricsMockRecorder) IncPostgresSet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncPostgresSet", reflect.TypeOf((*MockMetrics)(nil).IncPostgresSet))
}

// IncRequests mocks base method.
func (m *MockMetrics) IncRequests() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRequests")
}

// IncRequests indicates an expected call of IncRequests.
func (mr *MockMetricsMockRecorder) IncRequests() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRequests", reflect.TypeOf((*MockMetrics)(nil).IncRequests))
}

// SetKafkaStatus mocks base method.
func (m *MockMetrics) SetKafkaStatus(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKafkaStatus", arg0)
}

// SetKafkaStatus indicates an expected call of SetKafkaStatus.
func (mr *MockMetricsMockRecorder) SetKafkaStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKafkaStatus", reflect.TypeOf((*MockMetrics)(nil).SetKafkaStatus), arg0)
}

// SetPostgresStatus mocks base method.
func (m *MockMetrics) SetPostgresStatus(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPostgresStatus", arg0)
}

// SetPostgresStatus indicates an expected call of SetPostgresStatus.
func (mr *MockMetricsMockRecorder) SetPostgresStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPostgresStatus", reflect.TypeOf((*MockMetrics)(nil).SetPostgresStatus), arg0)
}
